trigger: 
- main
pool: 
  vmImage: 'AzurePipelines'
variables:
  buildConfiguration: 'Release'
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
